In [1]:
#Load required libraries
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split

In [2]:
#load Titanic csv file
Titanic_df = pd.read_csv('titanicdata.csv')

In [3]:
Titanic_df.head(10)

Survived  Pclass  Sex        Age
0         0       3    2  22.000000
1         1       1    1  38.000000
2         1       3    1  26.000000
3         1       1    1  35.000000
4         0       3    2  35.000000
5         0       3    2  29.699118
6         0       1    2  54.000000
7         0       3    2   2.000000
8         1       3    1  27.000000
9         1       2    1  14.000000

In [4]:
Y = np.array(Titanic_df[['Survived']])
print(len(Y))

891


In [5]:
Y[0:5]

array([[0],
       [1],
       [1],
       [1],
       [0]], dtype=int64)

In [6]:
X = (Titanic_df[['Pclass','Sex','Age','Survived']])

In [7]:
X[0:5]

Pclass  Sex   Age  Survived
0       3    2  22.0         0
1       1    1  38.0         1
2       3    1  26.0         1
3       1    1  35.0         1
4       3    2  35.0         0

In [8]:
cols_to_Normal = ['Pclass','Sex','Age']
X_new= X[cols_to_Normal]
X_new.head(10)

Pclass  Sex        Age
0       3    2  22.000000
1       1    1  38.000000
2       3    1  26.000000
3       1    1  35.000000
4       3    2  35.000000
5       3    2  29.699118
6       1    2  54.000000
7       3    2   2.000000
8       3    1  27.000000
9       2    1  14.000000

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.20 , random_state=42)

In [10]:
X_train

Pclass  Sex        Age
331       1    2  45.500000
733       2    2  23.000000
382       3    2  32.000000
704       3    2  26.000000
813       3    1   6.000000
..      ...  ...        ...
106       3    1  21.000000
270       1    2  29.699118
860       3    2  41.000000
435       1    1  14.000000
102       1    2  21.000000

[712 rows x 3 columns]

In [11]:
X_train, X_validation, y_train, y_validation = train_test_split(X_train, y_train, test_size=0.20 , random_state=42)

In [12]:
X_validation

Pclass  Sex        Age
373       1    2  22.000000
848       2    2  28.000000
593       3    1  29.699118
237       2    1   8.000000
36        3    2  29.699118
..      ...  ...        ...
516       2    1  34.000000
101       3    2  29.699118
783       3    2  29.699118
648       3    2  29.699118
554       3    1  22.000000

[143 rows x 3 columns]

In [13]:
X_new = X_train.apply( lambda rec:(rec - rec.mean())/rec.std(), axis =0)

In [14]:
type(X_new)

pandas.core.frame.DataFrame

In [15]:
X_new.head(10)
list(X_new)

['Pclass', 'Sex', 'Age']

In [16]:
X_new = np.array(X_new)
X_new[0:5]

array([[ 0.79265385,  0.71581825,  0.04404372],
       [ 0.79265385, -1.39454747,  0.04404372],
       [-0.41651516, -1.39454747,  0.29876877],
       [ 0.79265385, -1.39454747,  2.61383202],
       [-0.41651516, -1.39454747, -1.16743796]])

In [17]:
import random

In [18]:
def initialize_betas(dim):
#     b = random.random()
    w = np.random.rand(dim)
    return w

In [19]:
def sigmoid( w ,X_new):
    Z =  np.matmul(X_new,w)
    return (1.0 / (1 + np.exp(-Z)))

In [20]:
def get_cost( y, y_hat):
      #return np.sum(np.dot(y.T,np.log(1-y_hat)+ np.dot((1-y).T,np.log(1-y_hat)))) / ( len(y))
        return - np.sum(np.dot(y.T,np.log(1-y_hat)+ np.dot((1-y).T,np.log(1-y_hat)))) / ( len(y))
Y.shape
print(len(y_train))
# y_hat.shape

569


In [21]:
def update_beta ( w_0 , y , y_hat, X_new, alpha):
#     db = np.sum( y_hat - y)/ len(y)
#     b_0 = b_0 - alpha * db
    dw = np.dot((y_hat - y), X_new)/ len(y)
    w_0 = w_0 - alpha * dw
   
   
    return w_0

In [22]:
def accuracy(X_test,y_test):
    # Making predictions
    X_test_norm =X_test.apply( lambda rec:(rec - rec.mean())/rec.std(), axis =0)
    oneVector = np.ones((X_test_norm.shape[0], 1))
    X_test_norm = np.concatenate((oneVector, X_test_norm), axis=1)
    y_pred = sigmoid(w,X_test_norm)
    y_pred = [1 if p >= 0.5 else 0 for p in y_pred]
    # The accuracy
    accuracy = 0
    for i in range(len(y_pred)):
        if y_pred[i] == y_test[i]:
            accuracy += 1
#     print(f"Accuracy = {(accuracy / len(y_pred))*100}%")
    return (accuracy / len(y_pred))

In [23]:
oneVector = np.ones((X_new.shape[0], 1))
X_new = np.concatenate((oneVector, X_new), axis=1)
X_new[0:5]

array([[ 1.        ,  0.79265385,  0.71581825,  0.04404372],
       [ 1.        ,  0.79265385, -1.39454747,  0.04404372],
       [ 1.        , -0.41651516, -1.39454747,  0.29876877],
       [ 1.        ,  0.79265385, -1.39454747,  2.61383202],
       [ 1.        , -0.41651516, -1.39454747, -1.16743796]])

In [24]:
w = initialize_betas(X_new.shape[1])
print(w)

[0.57095622 0.65862415 0.30589089 0.03519016]


In [25]:
w.shape

(4,)

In [26]:
y_hat = sigmoid(w,X_new)

y_hat[0:5]

array([0.78810315, 0.66105243, 0.47017635, 0.68101038, 0.45734582])

In [27]:
# Reshape Y
y_train=y_train.reshape(len(y_train), )
current_cost= get_cost(y_train,y_hat)
#print(current_cost)
y_train.shape

(569,)

In [28]:
alpha = accuracy(X_validation,y_validation)
alpha = "{:.2f}".format(alpha)
print(alpha)

#(X_new).shape

0.26


In [29]:
w = update_beta (w, y_train, y_hat,X_new, float(alpha))

w.shape

(4,)

In [30]:
w

array([0.50482035, 0.57692992, 0.21836301, 0.04097473])

In [31]:
num_iterations = 500
alpha = 0.5

all_costs = []
w = initialize_betas(X_new.shape[1])
print("initial guess of  w: " , w)

for each_iter in range (num_iterations ):
    y_hat = sigmoid( w , X_new)
    current_cost = get_cost (y_train, y_hat)
#     prev_b = b
    prev_w = w
    w = update_beta ( prev_w, y_train, y_hat, X_new, alpha)
    all_costs.append(current_cost)
    if each_iter % 10 == 0:
        print('Iteration: ', each_iter, 'Cost: ', current_cost)
        each_iter += 1
    
#print('b_0:', b_0, 'b_1:',b_1,'b_2:',b_2,'b_3:',b_3,'b_4:', b_4, 'b_5:',b_5,'b_6:',b_6,'b_7:',b_7,'b_8:',b_8,'b_9:',b_9)
print("Final estimates of w is : ",w)

initial guess of  w:  [0.45775603 0.49683244 0.03608129 0.60201482]
Iteration:  0 Cost:  144.29394903163723
Iteration:  10 Cost:  63.17889850092078
Iteration:  20 Cost:  50.66352962488098
Iteration:  30 Cost:  46.84292171576122
Iteration:  40 Cost:  45.257584688825645
Iteration:  50 Cost:  44.493347925656195
Iteration:  60 Cost:  44.0885037724227
Iteration:  70 Cost:  43.859345129959365
Iteration:  80 Cost:  43.72330595334834
Iteration:  90 Cost:  43.63978145918263
Iteration:  100 Cost:  43.58729690651433
Iteration:  110 Cost:  43.55380054244506
Iteration:  120 Cost:  43.53220423270271
Iteration:  130 Cost:  43.51818938413371
Iteration:  140 Cost:  43.50905731246474
Iteration:  150 Cost:  43.50309196100857
Iteration:  160 Cost:  43.49918939589758
Iteration:  170 Cost:  43.49663412827847
Iteration:  180 Cost:  43.49496024519055
Iteration:  190 Cost:  43.493863478634545
Iteration:  200 Cost:  43.493144784763025
Iteration:  210 Cost:  43.49267382806608
Iteration:  220 Cost:  43.4923652195

In [32]:
accuracy = "{:.2f}".format(accuracy(X_test,y_test))
print(float(accuracy)*100,"%")

82.0 %
