In [1]:
#Load required libraries
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split

In [2]:
#load Titanic csv file
Titanic_df = pd.read_csv('titanicdata.csv')

In [3]:
Titanic_df.head(10)

Survived  Pclass  Sex        Age
0         0       3    2  22.000000
1         1       1    1  38.000000
2         1       3    1  26.000000
3         1       1    1  35.000000
4         0       3    2  35.000000
5         0       3    2  29.699118
6         0       1    2  54.000000
7         0       3    2   2.000000
8         1       3    1  27.000000
9         1       2    1  14.000000

In [4]:
X = (Titanic_df[['Pclass','Sex','Age','Survived']])

In [5]:
X[0:5]

Pclass  Sex   Age  Survived
0       3    2  22.0         0
1       1    1  38.0         1
2       3    1  26.0         1
3       1    1  35.0         1
4       3    2  35.0         0

In [6]:
Y = np.array(Titanic_df[['Survived']])
print(len(Y))

891


In [7]:
Y[0:5]

array([[0],
       [1],
       [1],
       [1],
       [0]], dtype=int64)

In [8]:
cols_to_Normal = ['Pclass','Sex','Age']
X_new= X[cols_to_Normal]
X_new.head(10)

Pclass  Sex        Age
0       3    2  22.000000
1       1    1  38.000000
2       3    1  26.000000
3       1    1  35.000000
4       3    2  35.000000
5       3    2  29.699118
6       1    2  54.000000
7       3    2   2.000000
8       3    1  27.000000
9       2    1  14.000000

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_new, Y, test_size=0.20 , random_state=42)

In [10]:
X_train

Pclass  Sex        Age
331       1    2  45.500000
733       2    2  23.000000
382       3    2  32.000000
704       3    2  26.000000
813       3    1   6.000000
..      ...  ...        ...
106       3    1  21.000000
270       1    2  29.699118
860       3    2  41.000000
435       1    1  14.000000
102       1    2  21.000000

[712 rows x 3 columns]

In [11]:
X_new = X_train.apply( lambda rec:(rec - rec.mean())/rec.std(), axis =0)

In [12]:
type(X_new)

pandas.core.frame.DataFrame

In [13]:
X_new.head(10)
list(X_new)

['Pclass', 'Sex', 'Age']

In [14]:
X_new = np.array(X_new)
X_new[0:5]

array([[-1.6130021 ,  0.72380138,  1.22834396],
       [-0.40026979,  0.72380138, -0.50315143],
       [ 0.81246252,  0.72380138,  0.18944673],
       [ 0.81246252,  0.72380138, -0.27228537],
       [ 0.81246252, -1.37965405, -1.81139239]])

In [15]:
import random

In [16]:
def initialize_betas(dim):
#     b = random.random()
    w = np.random.rand(dim)
    return w

In [17]:
oneVector = np.ones((X_new.shape[0], 1))
X_new = np.concatenate((oneVector, X_new), axis=1)
X_new[0:5]

array([[ 1.        , -1.6130021 ,  0.72380138,  1.22834396],
       [ 1.        , -0.40026979,  0.72380138, -0.50315143],
       [ 1.        ,  0.81246252,  0.72380138,  0.18944673],
       [ 1.        ,  0.81246252,  0.72380138, -0.27228537],
       [ 1.        ,  0.81246252, -1.37965405, -1.81139239]])

In [18]:
w = initialize_betas(X_new.shape[1])
print(w)

[0.56438748 0.99768074 0.3019964  0.63092311]


In [19]:
w.shape

(4,)

In [20]:
def sigmoid( w ,X_new):
    Z =  np.matmul(X_new,w)
    return (1.0 / (1 + np.exp(-Z)))

In [21]:
y_hat = sigmoid(w,X_new)

y_hat[0:5]

array([0.4871784 , 0.51653935, 0.84723501, 0.80561417, 0.45399692])

In [22]:
Y[0:5]

array([[0],
       [1],
       [1],
       [1],
       [0]], dtype=int64)

In [23]:
def get_cost( y, y_hat):
      #return np.sum(np.dot(y.T,np.log(1-y_hat)+ np.dot((1-y).T,np.log(1-y_hat)))) / ( len(y))
        return - np.sum(np.dot(y.T,np.log(1-y_hat)+ np.dot((1-y).T,np.log(1-y_hat)))) / ( len(y))
Y.shape
print(len(y_train))
# y_hat.shape

712


In [24]:
# Reshape Y
y_train=y_train.reshape(len(y_train), )
current_cost= get_cost(y_train,y_hat)
#print(current_cost)
y_train.shape

(712,)

In [25]:
def update_beta ( w_0 , y , y_hat, X_new, alpha):
#     db = np.sum( y_hat - y)/ len(y)
#     b_0 = b_0 - alpha * db
    dw = np.dot((y_hat - y), X_new)/ len(y)
    w_0 = w_0 - alpha * dw
   
   
    return w_0

In [26]:
alpha = 0.1

type(y_hat)
#(X_new).shape

numpy.ndarray

In [27]:
w = update_beta (w, y_train, y_hat,X_new, alpha)

w.shape

(4,)

In [28]:
w

array([0.54038013, 0.96461806, 0.26613174, 0.62232372])

In [29]:
num_iterations = 500
alpha = 0.1

all_costs = []
w = initialize_betas(X_new.shape[1])
print("initial guess of  w: " , w)

for each_iter in range (num_iterations ):
    y_hat = sigmoid( w , X_new)
    current_cost = get_cost (y_train, y_hat)
#     prev_b = b
    prev_w = w
    w = update_beta ( prev_w, y_train, y_hat, X_new, alpha)
    all_costs.append(current_cost)
    if each_iter % 10 == 0:
        print('Iteration: ', each_iter, 'Cost: ', current_cost)
        each_iter += 1
    
#print('b_0:', b_0, 'b_1:',b_1,'b_2:',b_2,'b_3:',b_3,'b_4:', b_4, 'b_5:',b_5,'b_6:',b_6,'b_7:',b_7,'b_8:',b_8,'b_9:',b_9)
print("Final estimates of w is : ",w)

initial guess of  w:  [0.40530296 0.75484721 0.55932395 0.21217135]
Iteration:  0 Cost:  209.29093693614365
Iteration:  10 Cost:  157.21965574996025
Iteration:  20 Cost:  123.47266472854356
Iteration:  30 Cost:  102.57485337310848
Iteration:  40 Cost:  89.47423176617211
Iteration:  50 Cost:  80.93172974885195
Iteration:  60 Cost:  75.10475852138865
Iteration:  70 Cost:  70.96075124254169
Iteration:  80 Cost:  67.90590069387653
Iteration:  90 Cost:  65.58521052415861
Iteration:  100 Cost:  63.77767358192796
Iteration:  110 Cost:  62.340341886191474
Iteration:  120 Cost:  61.17749691925882
Iteration:  130 Cost:  60.22302967300138
Iteration:  140 Cost:  59.43000701706718
Iteration:  150 Cost:  58.76428525490706
Iteration:  160 Cost:  58.20048027553935
Iteration:  170 Cost:  57.719353239703615
Iteration:  180 Cost:  57.30607119734412
Iteration:  190 Cost:  56.94902283686529
Iteration:  200 Cost:  56.638995001365885
Iteration:  210 Cost:  56.36858887277231
Iteration:  220 Cost:  56.13179863

In [30]:
# Making predictions
X_test_norm =X_test.apply( lambda rec:(rec - rec.mean())/rec.std(), axis =0)
oneVector = np.ones((X_test_norm.shape[0], 1))
X_test_norm = np.concatenate((oneVector, X_test_norm), axis=1)
y_pred = sigmoid(w,X_test_norm)
y_pred = [1 if p >= 0.5 else 0 for p in y_pred]

In [31]:
# The accuracy
accuracy = 0
for i in range(len(y_pred)):
    if y_pred[i] == y_test[i]:
        accuracy += 1
print(f"Accuracy = {accuracy / len(y_pred)}")
accuracy = "{:.2f}".format(accuracy / len(y_pred))
print(float(accuracy)*100,"%")

Accuracy = 0.8044692737430168
80.0 %
